#! /usr/bin/env bash

echo "== Delete objects"

# Exit immediately if any command returns non zero status
set -e

# Check for bucket name
if [ -z "$1" ]; then
    echo "No bucket name provided"
    exit 1
fi

aws s3api list-objects-v2 \
--bucket $1 \
--query Contents[].Key \
| jq -n '{Objects: [inputs | .[] | {Key: .} ]}' > object_list.json

aws s3api delete-objects \
--bucket $1 \
--delete file://object_list.json
