#! /usr/bin/env bash

echo "== List buckets"

# List bucketss and sort them based on Creation date decending order
# aws s3api list-buckets - returns json response
aws s3api list-buckets | jq -r '.Buckets | sort_by(.CreationDate) | reverse | .[0:10] | .[] | .Name'