#! /usr/bin/env bash

echo "== Put object"

# Exit immediately if any command returns non zero status
set -e

# Check for bucket name
if [ -z "$1" ]; then
    echo "No bucket name provided"
    exit 1
fi

# Check for file name
if [ -z "$2" ]; then
    echo "No file name provided"
    exit 1
fi

OBJECT_KEY=$(basename $2)

aws s3api put-object \
--bucket $1 \
--body $2 \
--key $OBJECT_KEY